Add Continuous Delivery for LinuxBrokerPackager & Java Linux Broker Test App
AzureAD/android-complete pull request #122
Opened 2021-12-17 13:39 UTC by wainaina

Adds:
 - Linux Broker Package project
 - Java Linux Broker Test App project 
to the continuous delivery pipeline.

The packages are assembled, and packaged using <PROJECTNAME>:buildDeb, 

Then the packages are published as pipeline artifacts that can then be consumed by the publishing pipeline for publishing on packages.microsoft.com
Pipeline link: https://identitydivision.visualstudio.com/DefaultCollection/Engineering/_build?definitionId=1515

Deb publisher link: https://identitydivision.visualstudio.com/IDDP/_build?definitionId=1447&_a=summary

2021-12-17 18:12 UTC, iamgusain requested changes

2021-12-17 18:12 UTC, iamgusain commented on azure-pipelines/continuous-delivery/auth-client-android-dev.yml
> +        - task: CopyFiles@2
We can use this pipeline to publish directly to packages.micrsoft.com, instead of publishing artifacts here and then using another pipeline to do the actual publish.

You can create a template for publishing to packages.microsoft.com and then use that template in this file.

2021-12-17 18:12 UTC, iamgusain commented on azure-pipelines/continuous-delivery/auth-client-android-dev.yml
> +          displayName: Build and publish java linux broker test app
I was thinking using this pipeline only for our production libraries consumed by our partners/customers and create a separate pipeline for all the test apps. 
Can you create a separate pipeline auth-client-android-testapps.yml and move it there?

2021-12-20 14:16 UTC, wainaina commented on azure-pipelines/continuous-delivery/auth-client-android-dev.yml
> +        - task: CopyFiles@2
Unless we publish to a different repo on packages.microsoft.com. Currently, the publishing pipelines point to prod repos.

2022-01-21 00:11 UTC, shahzaibj commented on azure-pipelines/continuous-delivery/auth-client-android-dev.yml
> +        - task: CopyFiles@2
We should actually not be publishing to `packages.microsoft.com` from continous delivery pipeline. My understanding is that this runs daily? For publishing to packages, we would want to be more explicit about when we publish and probably should have a dedicated pipeline that runs at-will.

2022-02-04 09:26 UTC, wainaina commented on azure-pipelines/continuous-delivery/auth-client-android-dev.yml
> +          displayName: Build and publish java linux broker test app
Removing the Java Linux Test App.

2022-02-04 17:39 UTC, iamgusain commented on versioning/version.properties
> +#Thu Sep 02 18:50:06 PDT 2021
Why do we need this and the version_tasks.gradle file in android-complete?

2022-02-04 17:49 UTC, iamgusain commented on azure-pipelines/continuous-delivery/auth-client-android-dev.yml
> +        - task: CopyFiles@2
Does that mean we don't need to publish the deb daily, in that case we probably don't need this task here.

2022-02-04 17:50 UTC, shahzaibj commented on azure-pipelines/continuous-delivery/auth-client-android-dev.yml
> +        - task: CopyFiles@2
We want a deb daily but only as a pipeline artifact (we don't want that to get pushed to `packages.microsoft.com`)

2022-02-08 16:53 UTC, wainaina commented on versioning/version.properties
> +#Thu Sep 02 18:50:06 PDT 2021
Removed.

2022-02-08 16:58 UTC, wainaina commented on azure-pipelines/continuous-delivery/auth-client-android-dev.yml
> +        - task: CopyFiles@2
We shall have 2 publishing events:
1. Publishing to the pipeline. - Only one in this pipeline
2. Publishing to packages.microsoft.com
Candidate builds that are chosen to be published are ran through another pipeline with more tasks to publish these packages to the artifact repo.

2022-02-08 17:03 UTC, shoatman approved these changes

2022-02-08 17:48 UTC, iamgusain commented on azure-pipelines/continuous-delivery/auth-client-android-dev.yml
> +        - task: CopyFiles@2
Is the plan to consume the pipeline artifact on daily/ongoing basis to do some validations (automation/ self host/dogfood) or only when we need to publish it to pkg.msft.com.

2022-02-08 17:55 UTC, shahzaibj commented on azure-pipelines/continuous-delivery/auth-client-android-dev.yml
> +        - task: CopyFiles@2
@iamgusain Yes, we would use these for automation and self host.

2022-02-08 17:56 UTC, iamgusain approved these changes

2022-02-16 11:48 UTC, merged