Release Pipeline stage refactoring, update displayNames for certain stages for android-complete pipelines
AzureAD/android-complete pull request #188
Opened 2023-02-10 03:40 UTC by fadidurah

This PR is to improve usability of Release and Daily pipelines and make them more readable. PR includes the following changes:

- Collect all test app generation jobs in release pipeline (automation apps, azure samples, brokerhosts) into one stage to allow users to quickly ignore that stage if needed.
- Collect UI automation jobs into their own configuration stages (ADAL w/ broker, RC MSAL PROD Broker, PROD MSAL RC Broker)
- Add boolean parameters for:
  - publishing libraries
  - running UI validation
  - promoting libraries
  - building broker apk
- Adjust condition fields to be able to cancel stages when pipeline is cancelled (this is because custom condition statements override the default condition assigned to all stages)
- Update stage dependency structure
- Add stage to combine code coverage reports in daily pipeline
- General changes to make pipeline more readable

Old Release Pipeline Structure: https://identitydivision.visualstudio.com/Engineering/_build/results?buildId=1050405&view=results
Release Pipeline after this refactoring: https://identitydivision.visualstudio.com/Engineering/_build/results?buildId=1051175&view=results

2023-02-14 21:24 UTC, iamgusain commented on azure-pipelines/continuous-delivery/auth-client-android-dev.yml
> +    - publishMsal
Add publishLinux and publishAdal as dependencies for this stage

2023-02-14 21:26 UTC, iamgusain commented on azure-pipelines/continuous-delivery/auth-client-android-dev.yml
>    displayName: Promote published packages
Can you remove the step for publishing to "Release" view from this stage. We don't need it anymore as both CP and AuthApp can consume Prerelease view now.

2023-02-14 21:28 UTC, iamgusain commented on azure-pipelines/ui-automation/broker-release.yml
>      - generated
Can you also add brief description to what the version number looks like for each of these.

- generated (by the pipeline in format $(Build.BuildId)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

- unique (as provided in the RC version parameters below)

2023-02-14 21:34 UTC, iamgusain commented on azure-pipelines/ui-automation/broker-release.yml
>              arguments: '-PackagingPAT "$(MSAZURE_BUILD_TOKEN)" -common4jVersion "${{ parameters.common4jVersionRC }}" -commonVersion "${{ parameters.commonVersionRC }}" -broker4jVersion "${{ paramete
We should use (System.AccessToken) here, Refer to how daily-pipeline is doing it.

2023-02-14 21:36 UTC, iamgusain commented on azure-pipelines/ui-automation/broker-release.yml
>      - template: ./templates/build-broker-host.yml
Add this to download Prod and RC broker, We should be downloading this from feed, instead of building.

2023-02-14 21:38 UTC, iamgusain commented on azure-pipelines/continuous-delivery/assemble&publish.yml
>        ${{ parameters.vstsMvnAndroidUsername }}: $(AndroidAuthClient-Internal-Maven-Username)
Can you change "$(AndroidAuthClient-Internal-Maven-Access-Token)" with "$(System.AccessToken)" in this file.
That will remove dependencies on personal tokens.

2023-02-14 21:39 UTC, iamgusain commented on azure-pipelines/continuous-delivery/assemble&publish.yml
>        ${{ parameters.vstsMvnAndroidUsername }}: $(AndroidAuthClient-Internal-Maven-Username)
it's mostly done in this file, just left in one place.

2023-02-14 21:42 UTC, iamgusain commented on azure-pipelines/continuous-delivery/auth-client-android-dev.yml
>        vstsMvnAndroidUsername: ENV_VSTS_MVN_ANDROIDCOMMON_USERNAME
We can get rid of these two params here. and set these in the assemble&publish.yml directly.
It will be even better if we could use the same name across all the repo build.gradle file.

2023-02-14 21:44 UTC, iamgusain requested changes
Left some comments. 
There are few more improvements that can be made. feel free to ping me to discuss,

2023-02-15 20:56 UTC, fadidurah commented on azure-pipelines/continuous-delivery/auth-client-android-dev.yml
>    displayName: Promote published packages
Sure, i'll do the same for the release pipeline

2023-02-16 03:08 UTC, fadidurah commented on azure-pipelines/continuous-delivery/auth-client-android-dev.yml
>        vstsMvnAndroidUsername: ENV_VSTS_MVN_ANDROIDCOMMON_USERNAME
These parameters are different across the libraries that call assemble@publish.yml though...

2023-02-16 04:06 UTC, fadidurah commented on azure-pipelines/ui-automation/broker-release.yml
>      - template: ./templates/build-broker-host.yml
Added publishing to universal packages when building prod brokerhost. Also added Brokerhost PROD download in download broker, removed "old BrokerHost", we don't actually use that anywhere.

2023-02-16 19:27 UTC, p3dr0rv commented on azure-pipelines/ui-automation/templates/flank/run-on-firebase-with-flank.yml
> +  - job: ${{ parameters.jobTitle }}
why are we exposing job title as a parameter?

2023-02-16 19:41 UTC, p3dr0rv commented on azure-pipelines/ui-automation/templates/build-azure-sample-app.yml
> +- job: azure_samples${{ parameters.packageVariant }}${{ parameters.productFlavors }}${{ parameters.signingConfigurations }}
why change the job names,?

2023-02-16 19:45 UTC, p3dr0rv approved these changes

2023-02-17 04:02 UTC, fadidurah commented on azure-pipelines/ui-automation/templates/flank/run-on-firebase-with-flank.yml
> +  - job: ${{ parameters.jobTitle }}
Yes, combining different templates into one singular stage makes this necessary, we would have duplicate job titles in the same stage, otherwise

2023-02-17 04:02 UTC, fadidurah commented on azure-pipelines/ui-automation/templates/build-azure-sample-app.yml
> +- job: azure_samples${{ parameters.packageVariant }}${{ parameters.productFlavors }}${{ parameters.signingConfigurations }}
can't have duplicate job names in the same stage. Adding parameters to these job names makes it possible to differentiate them based on build variant/flavor

2023-02-18 00:13 UTC, iamgusain commented on azure-pipelines/continuous-delivery/auth-client-android-dev.yml
>        vstsMvnAndroidUsername: ENV_VSTS_MVN_ANDROIDCOMMON_USERNAME
Yeah, I was thinking of updating those to same name. (can be done as separate change).
an intermediate step could be to set all of these in assemble&publish.yml as a separate step, instead of taking individual as parameter

2023-02-18 00:14 UTC, iamgusain approved these changes

2023-02-18 02:00 UTC, merged