Update auth-client-android-dev.yml for Azure Pipelines
AzureAD/android-complete pull request #207
Opened 2023-05-12 20:35 UTC by tanmaymanolkar1

2023-05-18 17:07 UTC, iamgusain commented on azure-pipelines/continuous-delivery/assemble&publish.yml
> +    enabled: false
remove temp changes before merging

2023-05-18 17:08 UTC, iamgusain requested changes
Remove temporary/test changes before mergin

2023-05-19 02:07 UTC, tanmaymanolkar1 commented on azure-pipelines/continuous-delivery/assemble&publish.yml
> +    enabled: false
removed

2023-05-19 02:13 UTC, tanmaymanolkar1 commented
> Remove temporary/test changes before mergin

ack

2023-05-19 11:36 UTC, fadidurah commented on azure-pipelines/continuous-delivery/assemble&publish.yml
> +- name: testParams
I think renaming this to something like "linuxTestParams" is more clear

2023-05-19 11:37 UTC, fadidurah approved these changes

2023-05-19 15:47 UTC, iamgusain commented on azure-pipelines/continuous-delivery/assemble&publish.yml
> +- name: testParams
I think testParams is fine, as we can also use it for other projects if needed

2023-05-19 15:50 UTC, iamgusain commented on azure-pipelines/continuous-delivery/assemble&publish.yml
> +          ./gradlew LinuxBroker:linuxBrokerUnitTestCoverageReport ${{ parameters.testParams}}
Do we need this to run test here?

2023-05-19 15:50 UTC, iamgusain commented on azure-pipelines/continuous-delivery/assemble&publish.yml
> +      condition: ne(${{ parameters.shouldRunLinuxInlineScript }}, 'True')
Why separate task for Linux?

2023-05-19 16:33 UTC, p3dr0rv commented on azure-pipelines/continuous-delivery/assemble&publish.yml
> +- name: shouldRunLinuxInlineScript
IMO we should get rid of this variable and just check if the project is LinuxBroker

2023-05-19 16:33 UTC, p3dr0rv commented on azure-pipelines/continuous-delivery/assemble&publish.yml
> +          ./gradlew LinuxBroker:linuxBrokerUnitTestCoverageReport ${{ parameters.testParams}}
yep, If this is just a set up for Linux broker we should remove this line

2023-05-19 17:12 UTC, tanmaymanolkar1 commented on azure-pipelines/continuous-delivery/assemble&publish.yml
> +          ./gradlew LinuxBroker:linuxBrokerUnitTestCoverageReport ${{ parameters.testParams}}
yeah we need to to activate the keyring, I tried removing it and the test cases they fail in the separate testing job

2023-05-19 17:13 UTC, tanmaymanolkar1 commented on azure-pipelines/continuous-delivery/assemble&publish.yml
> +- name: testParams
yes testParams is more for a generic use

2023-05-19 17:14 UTC, tanmaymanolkar1 commented on azure-pipelines/continuous-delivery/assemble&publish.yml
> +- name: shouldRunLinuxInlineScript
this parameter particularly set to make sure we run the script only when needed, we have other jobs like Linux Broker publishing where we wouldnt want the associated script to run.

2023-05-19 17:16 UTC, tanmaymanolkar1 commented on azure-pipelines/continuous-delivery/assemble&publish.yml
> +      condition: eq(${{ parameters.shouldRunLinuxInlineScript }}, 'True')
I have added a separate flag to make sure we can separate out specific tasks in Linux Broker, it is a better to have flag which we can mend to particularly run the associated scripts.

2023-05-19 17:19 UTC, tanmaymanolkar1 commented on azure-pipelines/continuous-delivery/assemble&publish.yml
> +      condition: ne(${{ parameters.shouldRunLinuxInlineScript }}, 'True')
I will get the tasks merged

2023-05-19 20:02 UTC, tanmaymanolkar1 commented
> 

Updated

2023-05-19 20:02 UTC, tanmaymanolkar1 commented
> BTW I think the test task is incorrect. it should use ${{ parameters.testParams}}
> 
> tasks: ${{ parameters.project }}:${{ parameters.testCmd}} _${{ parameters.assembleParams}}_ -Psugar=true -PlabSecret=$(AndroidAutomationRunnerAppSecret) -PshouldSkipLongRunningTest=true -PcodeCoverageEnabled=true

Updated

2023-05-19 20:06 UTC, p3dr0rv approved these changes

2023-05-19 20:11 UTC, tanmaymanolkar1 commented
> Remove temporary/test changes before mergin

Noted

2023-05-19 20:12 UTC, merged

2023-05-19 20:32 UTC, fadidurah commented on azure-pipelines/continuous-delivery/assemble&publish.yml
> +- name: testParams
Ahh I see. When I first looked at it it was only being used under the Linux script condition. Now that's used for all the params, this naming is fine.