Download old Msal & OneAuth Test apps
AzureAD/android-complete pull request #220
Opened 2023-06-09 07:30 UTC by cikelengfeng

Add parameters to the “Android Broker CI” pipeline to pass old versions of MsalTestApp and OneAuthTestApp. 

Add file paths of old version test app apks to the following stages: 

msal_with_broker_high_api in the broker-test.yml file 

msal_with_brokerhost_high_api in the broker-test.yml file 

msal_with_broker_low_api in the broker-test.yml file

2023-06-19 01:46 UTC, somalaya commented on azure-pipelines/ui-automation/templates/download-old-test-apps.yml
> +      - script: mkdir oldTestApps
so are we creating a new folder with name olTestApps in the broker feed?

2023-06-19 02:30 UTC, cikelengfeng commented on azure-pipelines/ui-automation/templates/download-old-test-apps.yml
> +      - script: mkdir oldTestApps
No, this script is creating a new folder in pipeline's artifact directory so that the following task can download apks into this folder.

2023-06-19 03:18 UTC, fadidurah approved these changes

2023-06-19 15:33 UTC, somalaya commented on azure-pipelines/ui-automation/templates/download-old-test-apps.yml
> +      - script: mkdir oldTestApps
Where exactly are we going to maintain the old apks? Is it not going to be maintained in the feed?

2023-06-19 21:04 UTC, somalaya commented on azure-pipelines/ui-automation/templates/download-old-test-apps.yml
> +        artifact: oldtestapps
I did not understand why this task is required. Could you please elaborate?

2023-06-19 21:04 UTC, somalaya requested changes
Left a couple of comments

2023-06-20 01:41 UTC, cikelengfeng commented on azure-pipelines/ui-automation/templates/download-old-test-apps.yml
> +        artifact: oldtestapps
Had a offline conversation with Sowmya, we need to download the old test apps from the Android-Broker feed not the BrokerE2ETestApps feed, and I also removed unnecessary "push msal/oneauth test app to BrokerE2ETestApps" tasks in the other PR.

2023-06-21 03:05 UTC, somalaya approved these changes

2023-06-21 04:31 UTC, merged